### PR TITLE
Introduced JournalDiskSyncStrategy that allows more control of journal F...

### PR DESCRIPTION
**Pull request by ghost**
See mailing list discussion.

http://sourceforge.net/p/prevayler/mailman/message/32698201/

### CODE REVIEW

**Comment by cbuschka** [comment]
Moin, what has to be done for this request being pulled in?

**Comment by karlwettin** [comment]
Moin moin. I'm afraid no one but me found this very useful or interesting. Perhaps it could trigger a new discussion or vote if you too explained how you'd use it and why it'd be a good thing.

**Comment by cklemkeberlin** [comment]
Hi, I've just created a pull request for a larger commit regarding better type-safety. I have also incorporated your modifications (with minor adaptions), so they are indirectly part of my pull request. Let's see what Mr Sampson thinks about the package. I hope to get at least some kind of reply from him.

**Comment by jsampson** [comment]
Hi @cklemkeberlin,

Thanks for the awesome work on cleaning up raw types! It'll take a few days to review all of that, but I'm looking forward to it.

As for this particular change, we did have a lengthy discussion on the mailing list at the time:

https://sourceforge.net/p/prevayler/mailman/prevayler-discussion/thread/1E36E492-8D1D-45E6-8FD9-2A3AB9AE7E94%40kodapan.se/

Perhaps we should have summarized the discussion here and closed the pull request. Klaus and I suggested some alternative approaches, which Karl wasn't quite happy with. But without digging into his actual code ourselves, we couldn't quite convince each other.

Do you have your own use case for the functionality introduced in this pull request? If so, please describe it to us so that we can consider it more fully!

By the way, Karl (the author of this pull request) is a project committer himself, so it's not like this was just sitting here waiting for a reply from me. :)

Cheers,
Justin

**Comment by jsampson** [comment]
@karlwettin - Now that this is brought back to our attention, I thought about it some more and have a more nuanced reaction. While the JournalDiskSyncStrategy itself seemed a little too complicated to me, I think it's reasonable to try to expose a `sync()` method somewhere. I see that's part of what your change was doing.

If we were to keep the simple `boolean journalDiskSync` mechanism from before, but expose a `sync()` method, I am imagining that you could have configured `journalDiskSync` as `false` and then explicitly called `sync()` after every batch of transactions that you were describing in the mailing list thread. Would that have worked for you?

**Comment by jsampson** [comment]
After thinking about it further, I don't see a tidy way to expose a `sync()` method, but perhaps we could provide a ForceSync annotation that can be applied to any Transaction or TransactionWithQuery. The idea would be that whenever a batch being written to disk in DurableOutputStream contains a transaction marked with ForceSync, that batch will be sync'd before returning. We could even provide a final JustForceSync transaction implementation that is otherwise a no-op. The public API would look like this:

```
@Target(TYPE)
@Retention(RUNTIME)
@Inherited
@Documented
public @interface ForceSync {}

@ForceSync
public final class JustForceSync implements Transaction<Object> {
    public void executeOn(Object prevalentSystem, Date executionTime) {}
}
```

**Comment by klauswuestefeld** [comment]
Seems to me the only complete and non-leaky way to do it is
   boolean Transaction.mustSync()
or
   boolean SyncStrategy.mustSync(transaction).

**Comment by jsampson** [comment]
@klauswuestefeld - For the first, do you mean adding an instance method to the Transaction interface? That wouldn't seem to be backward-compatible with existing Transaction implementations. How would it be better than a `@ForceSync` (or `@MustSync` to use your wording) annotation?

**Comment by klauswuestefeld** [comment]
Can the annotation be applied on an instance and not on a class? (Not
rhetorical)

**Comment by jsampson** [comment]
Ah, no, the annotation would apply to classes rather than instances. I was only imagining use cases where a particular _type_ of transaction would determine the syncing behavior, but now I understand what you mean by _complete_.

Thinking through the likely implementation, a method on Transaction would end up being a bit simpler as well. It would have to apply to TransactionWithQuery as well, which actually means that the method would fit nicely on the recently-introduced [TransactionBase](https://github.com/prevayler/prevayler/blob/master/core/src/main/java/org/prevayler/TransactionBase.java).

Furthermore, the backward-compatibility concern can be mitigated by declaring a default implementation returning `false`, once we upgrade to Java 8. That would imply moving this to Prevayler 2.8. How does that sound?

**Comment by klauswuestefeld** [comment]
Sounds good.

I believe we should default to durability, though, not to speed.

**Comment by jsampson** [comment]
> Sounds good.

Okay, I've moved this from the 2.7 board to the 2.8 board.

> I believe we should default to durability, though, not to speed.

Are you referring to my suggestion that `mustSync()` would default to `false`? I certainly agree with you about preferring durability over speed, but I think that's covered by the fact that `journalDiskSync` already defaults to `true`. If someone sets `journalDiskSync` to `false`, then the current behavior is that no transactions force a sync. Therefore I believe that the current behavior is preserved by having the new `mustSync()` method default to `false`. Users who leave `journalDiskSync` set to `true` don't need to worry about it, because `mustSync()` will be ignored.

**Comment by klauswuestefeld** [comment]
I see.

It seems we are tainting the new mechanism because of backward
compatibility.

Maybe we could deprecate journalDiskSync and:
If it is set (deprecated behaviour) it will be used and
transaction.shouldSync() will not.
If it is not set (new behaviour) we use transaction.shouldSync() defaulting
to true.

So you can use on or the other. You dont have to know about the interaction
of both.

What do you think?

**Comment by jsampson** [comment]
I've created a new issue #23, so that we can close this pull request and continue the discussion of design options on the issue. I'll post more thoughts over there later!

**Pull request closed without merging**
